from demo import sayhi
print("Hello world")
print("This is git and jenkin tutorial")
print("stagging difference")
print("Hello python")
print("Git and jenkin connected")
print("New folder added")
print("")
print("New text file added")
a=sayhi()
print(a)